window.google_ad_status = 1;

/*
     FILE ARCHIVED ON 07:47:33 Dec 02, 2015 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 22:09:34 Mar 04, 2018.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/